import { useEffect, useState } from 'react';
import type { AppSettings, MasterKeySource } from '@autonomy-studio/shared';
import { getSettings } from '../api/settings';
import { ThemeToggle } from '../theme/ThemeToggle';

/**
 * How the key got here, in a sentence — one per member of the shared union, as
 * a total `Record` rather than a `switch` with a default. A fourth source added
 * server-side then fails to COMPILE here, instead of rendering a raw enum value
 * or falling through to a generic sentence that quietly says nothing.
 */
const MASTER_KEY_SOURCE_LABEL: Record<MasterKeySource, string> = {
  env: 'Provided by the AUTONOMY_MASTER_KEY environment variable',
  file: 'Loaded from a key file',
  generated: 'Auto-generated by this server on first run',
};

/**
 * The Settings surface (U15 slice 2, #1094) — `#/settings`.
 *
 * Two things, and the second is why the page exists.
 *
 * APPEARANCE re-renders the rail's own `ThemeToggle`, sharing its store rather
 * than owning a second copy of the state. It is the second consumer that
 * toggle's docblock predicted; the two switches show one value because they
 * read one store. Note for anyone querying by role: the accessible name "Dark
 * mode" is now AMBIGUOUS document-wide on this route, so specs scope to the
 * rail (`e2e/support/theme.ts`) or to this page.
 *
 * SECRET ENCRYPTION reports where the master key came from. `resolveMasterKey`
 * mints one on first run when it finds neither env var nor key file, and warns
 * that the file it just wrote now encrypts every secret at rest and must be
 * backed up — a warning that goes to the server log and nowhere else, so an
 * operator running this as a service or a container has never seen it. Losing
 * that file makes every stored secret permanently undecryptable: versions are
 * immutable and there is no recovery path, only re-entry of every credential.
 * That is the one sentence this page is here to carry.
 *
 * The advisory is STATIC TEXT, not `role="alert"` or a live region. It is true
 * at load and never changes, so there is nothing to announce; a live region
 * would have a screen reader narrate it on every visit as though it had just
 * happened. `VersionBadge` made the same call for the same reason.
 */
export function SettingsPage() {
  const [settings, setSettings] = useState<AppSettings | null>(null);
  const [error, setError] = useState<Error | null>(null);

  useEffect(() => {
    const controller = new AbortController();
    /* Two-argument `then`, not `.then().catch()`: a chained `catch` also
       catches anything the success handler throws, reporting a render-side bug
       as a failed load. The abort check is on the SUCCESS branch too — a fetch
       that resolves just as the effect tears down would otherwise set state on
       an unmounted page. */
    getSettings(controller.signal).then(
      (loaded) => {
        if (controller.signal.aborted) return;
        setSettings(loaded);
        setError(null);
      },
      (cause: unknown) => {
        if (controller.signal.aborted) return;
        setError(cause instanceof Error ? cause : new Error(String(cause)));
      },
    );
    return () => controller.abort();
  }, []);

  const masterKey = settings?.masterKey ?? null;

  return (
    <>
      <div className="page-header">
        <h2>Settings</h2>
      </div>
      <p className="page-hint">How this server is configured, and how it looks.</p>

      <section aria-labelledby="settings-appearance" className="home-section">
        <h3 id="settings-appearance">Appearance</h3>
        <div className="settings-row">
          <ThemeToggle />
          {/* `aria-hidden`, because the switch's own `aria-label` is already
              this exact string — the rail shows it as a tooltip, and a page
              with room for it shows it as text. Left readable by AT, a screen
              reader would announce "Dark mode, switch" and then "Dark mode"
              again. */}
          <span aria-hidden="true">Dark mode</span>
        </div>
      </section>

      <section aria-labelledby="settings-secrets" className="home-section">
        <h3 id="settings-secrets">Secret encryption</h3>

        {error !== null && (
          <p role="alert" className="error">
            {error.message}
          </p>
        )}

        {/* `null` is "the read has not answered", which is NOT "there is no key"
            — the server cannot start without one. Saying nothing until it
            answers beats rendering a blank status that reads as an absence. */}
        {masterKey === null && error === null && <p>Loading…</p>}

        {masterKey !== null && (
          <>
            <dl className="run-meta">
              <dt>Master key</dt>
              <dd>{MASTER_KEY_SOURCE_LABEL[masterKey.source]}</dd>

              {masterKey.keyFilePath !== null && (
                <>
                  <dt>Key file</dt>
                  {/* `<code>` because it is a path to be copied verbatim. It
                      needs no wrap rule of its own: `.run-meta dd` already sets
                      `overflow-wrap: anywhere`, which is an INHERITED property,
                      so a long absolute path wraps rather than widening the
                      page. A duplicate rule here would read as load-bearing
                      while changing nothing. */}
                  <dd>
                    <code>{masterKey.keyFilePath}</code>
                  </dd>
                </>
              )}
            </dl>

            {masterKey.source === 'generated' && (
              <p className="status-advisory">
                This key was generated automatically and exists only in that file. It encrypts every
                secret stored here — back it up somewhere safe (a password manager, or your
                infrastructure&apos;s secret store). If the file is lost, every stored secret
                becomes permanently undecryptable and each one has to be entered again. To pin your
                own key instead, set AUTONOMY_MASTER_KEY or AUTONOMY_MASTER_KEY_FILE and restart.
              </p>
            )}
          </>
        )}
      </section>
    </>
  );
}
