import { afterEach, describe, expect, it, vi } from 'vitest';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import type { AppSettings, MasterKeySource } from '@autonomy-studio/shared';
import { SettingsPage } from './SettingsPage';
import { getSettings } from '../api/settings';
import { uiStore } from '../stores/uiStore';

vi.mock('../api/settings', async (importActual) => ({
  ...(await importActual<typeof import('../api/settings')>()),
  getSettings: vi.fn(),
}));

const getSettingsMock = vi.mocked(getSettings);

afterEach(() => {
  vi.clearAllMocks();
});

function settings(source: MasterKeySource, keyFilePath: string | null): AppSettings {
  return { masterKey: { source, keyFilePath } };
}

/** The advisory, matched on the consequence rather than on any one wording. */
function advisory() {
  return screen.queryByText(/permanently undecryptable/i);
}

describe('SettingsPage — secret encryption', () => {
  it('names the key file a generated key was written to, and says to back it up', async () => {
    getSettingsMock.mockResolvedValue(settings('generated', '/data/secrets/master.key'));
    render(<SettingsPage />);

    expect(
      await screen.findByText(/Auto-generated by this server on first run/),
    ).toBeInTheDocument();
    expect(screen.getByText('/data/secrets/master.key')).toBeInTheDocument();
    expect(advisory()).toBeInTheDocument();
  });

  /*
   * The advisory is about a key NOBODY CHOSE. An operator who mounted their own
   * key file has already made the backup decision, so repeating the warning
   * there would train them to ignore it in the one case that matters.
   */
  it('shows the key file for an operator-supplied key WITHOUT the advisory', async () => {
    getSettingsMock.mockResolvedValue(settings('file', '/etc/autonomy/master.key'));
    render(<SettingsPage />);

    expect(await screen.findByText(/Loaded from a key file/)).toBeInTheDocument();
    expect(screen.getByText('/etc/autonomy/master.key')).toBeInTheDocument();
    expect(advisory()).not.toBeInTheDocument();
  });

  it('reports an env-provided key with no file row at all', async () => {
    getSettingsMock.mockResolvedValue(settings('env', null));
    render(<SettingsPage />);

    expect(await screen.findByText(/AUTONOMY_MASTER_KEY environment variable/)).toBeInTheDocument();
    expect(screen.queryByText('Key file')).not.toBeInTheDocument();
    expect(advisory()).not.toBeInTheDocument();
  });

  /*
   * A failed read must not render as "no key". The server cannot start without
   * one, so a silent blank would be a false statement about the system — the
   * absent-fact-as-benign-default shape #473 was.
   */
  it('reports a failed read instead of an empty status', async () => {
    getSettingsMock.mockRejectedValue(new Error('offline'));
    render(<SettingsPage />);

    expect(await screen.findByRole('alert')).toHaveTextContent('offline');
    expect(screen.queryByText('Master key')).not.toBeInTheDocument();
  });
});

describe('SettingsPage — appearance', () => {
  it('carries a theme switch that flips the shared store', async () => {
    getSettingsMock.mockResolvedValue(settings('env', null));
    render(<SettingsPage />);

    /* The page renders the rail's own `ThemeToggle` against the SINGLETON
       store, which is the point — the two switches must show one value. It is
       the only switch in this isolated render, so no scoping is needed here;
       the whole-app specs scope to the rail instead. */
    const toggle = screen.getByRole('switch', { name: 'Dark mode' }) as HTMLInputElement;
    /* Fluent's `Switch` is a real `<input type="checkbox" role="switch">`, so
       its state is the `checked` PROPERTY — `aria-checked` is absent, and an
       assertion against it would compare null to null and pass with the store
       unwired. Read the starting value rather than assuming it: the toggle
       runs on the app-wide singleton, whose mode persists. */
    const before = toggle.checked;
    await userEvent.click(toggle);
    expect(toggle.checked).toBe(!before);
  });
});

describe('SettingsPage — density (#1477 OR29)', () => {
  afterEach(() => uiStore.getState().setDensity('compact'));

  it('starts compact, and a choice is the store’s', async () => {
    getSettingsMock.mockResolvedValue(settings('env', null));
    render(<SettingsPage />);
    const picker = screen.getByLabelText<HTMLSelectElement>('Density');
    expect(picker.value).toBe('compact');

    await userEvent.selectOptions(picker, 'Comfortable');
    expect(uiStore.getState().density).toBe('comfortable');
    expect(picker.value).toBe('comfortable');
  });
});

describe('SettingsPage — display time zone (#1484)', () => {
  afterEach(() => uiStore.getState().setDisplayTimeZone('local'));

  it('starts on local, and a chosen zone is the store’s and shows in the hint', async () => {
    getSettingsMock.mockResolvedValue(settings('env', null));
    render(<SettingsPage />);
    const picker = screen.getByLabelText<HTMLSelectElement>('Display time zone');
    expect(picker.value).toBe('local');
    expect(picker).toHaveAccessibleDescription(/^Times read like \d{4}-\d{2}-\d{2} /);

    await userEvent.selectOptions(picker, 'UTC');
    expect(uiStore.getState().displayTimeZone).toBe('UTC');
    expect(picker.value).toBe('UTC');
    expect(picker).toHaveAccessibleDescription(/^Times read like .* UTC$/);
  });

  it('keeps a stored zone the runtime does not list selectable, rather than dropping it', () => {
    getSettingsMock.mockResolvedValue(settings('env', null));
    // `Etc/GMT+5` formats but is not in `Intl.supportedValuesOf`'s list.
    uiStore.getState().setDisplayTimeZone('Etc/GMT+5');
    render(<SettingsPage />);
    expect(screen.getByLabelText<HTMLSelectElement>('Display time zone').value).toBe('Etc/GMT+5');
  });
});

/*
 * #1594 OR40 S6 — Settings on the design system: labels, not prose. Each
 * section is the one `Section`, a named region whose `?` says what it holds,
 * and no paragraph sits under the page title.
 */
describe('SettingsPage — design system', () => {
  it('has no prose under the title, and each section is a region described by its ?', async () => {
    getSettingsMock.mockResolvedValue(settings('env', null));
    const { container } = render(<SettingsPage />);
    await screen.findByText(/AUTONOMY_MASTER_KEY environment variable/);

    expect(container.querySelector('.page-hint')).toBeNull();
    for (const [name, about] of [
      ['Appearance', /theme, density and time zone/i],
      ['Secret encryption', /master key/i],
    ] as const) {
      const region = screen.getByRole('region', { name });
      expect(region).toHaveClass('section');
      expect(region).toHaveAccessibleDescription(about);
    }
  });
});
