import { afterEach, describe, expect, it, vi } from 'vitest';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import type { AppSettings, MasterKeySource } from '@autonomy-studio/shared';
import { SettingsPage } from './SettingsPage';
import { getSettings } from '../api/settings';

vi.mock('../api/settings', async (importActual) => ({
  ...(await importActual<typeof import('../api/settings')>()),
  getSettings: vi.fn(),
}));

const getSettingsMock = vi.mocked(getSettings);

afterEach(() => {
  vi.clearAllMocks();
});

function settings(source: MasterKeySource, keyFilePath: string | null): AppSettings {
  return { masterKey: { source, keyFilePath } };
}

/** The advisory, matched on the consequence rather than on any one wording. */
function advisory() {
  return screen.queryByText(/permanently undecryptable/i);
}

describe('SettingsPage — secret encryption', () => {
  it('names the key file a generated key was written to, and says to back it up', async () => {
    getSettingsMock.mockResolvedValue(settings('generated', '/data/secrets/master.key'));
    render(<SettingsPage />);

    expect(
      await screen.findByText(/Auto-generated by this server on first run/),
    ).toBeInTheDocument();
    expect(screen.getByText('/data/secrets/master.key')).toBeInTheDocument();
    expect(advisory()).toBeInTheDocument();
  });

  /*
   * The advisory is about a key NOBODY CHOSE. An operator who mounted their own
   * key file has already made the backup decision, so repeating the warning
   * there would train them to ignore it in the one case that matters.
   */
  it('shows the key file for an operator-supplied key WITHOUT the advisory', async () => {
    getSettingsMock.mockResolvedValue(settings('file', '/etc/autonomy/master.key'));
    render(<SettingsPage />);

    expect(await screen.findByText(/Loaded from a key file/)).toBeInTheDocument();
    expect(screen.getByText('/etc/autonomy/master.key')).toBeInTheDocument();
    expect(advisory()).not.toBeInTheDocument();
  });

  it('reports an env-provided key with no file row at all', async () => {
    getSettingsMock.mockResolvedValue(settings('env', null));
    render(<SettingsPage />);

    expect(await screen.findByText(/AUTONOMY_MASTER_KEY environment variable/)).toBeInTheDocument();
    expect(screen.queryByText('Key file')).not.toBeInTheDocument();
    expect(advisory()).not.toBeInTheDocument();
  });

  /*
   * A failed read must not render as "no key". The server cannot start without
   * one, so a silent blank would be a false statement about the system — the
   * absent-fact-as-benign-default shape #473 was.
   */
  it('reports a failed read instead of an empty status', async () => {
    getSettingsMock.mockRejectedValue(new Error('offline'));
    render(<SettingsPage />);

    expect(await screen.findByRole('alert')).toHaveTextContent('offline');
    expect(screen.queryByText('Master key')).not.toBeInTheDocument();
  });
});

describe('SettingsPage — appearance', () => {
  it('carries a theme switch that flips the shared store', async () => {
    getSettingsMock.mockResolvedValue(settings('env', null));
    render(<SettingsPage />);

    /* The page renders the rail's own `ThemeToggle` against the SINGLETON
       store, which is the point — the two switches must show one value. It is
       the only switch in this isolated render, so no scoping is needed here;
       the whole-app specs scope to the rail instead. */
    const toggle = screen.getByRole('switch', { name: 'Dark mode' }) as HTMLInputElement;
    /* Fluent's `Switch` is a real `<input type="checkbox" role="switch">`, so
       its state is the `checked` PROPERTY — `aria-checked` is absent, and an
       assertion against it would compare null to null and pass with the store
       unwired. Read the starting value rather than assuming it: the toggle
       runs on the app-wide singleton, whose mode persists. */
    const before = toggle.checked;
    await userEvent.click(toggle);
    expect(toggle.checked).toBe(!before);
  });
});
