import { expect, test } from '@playwright/test';
import { collectPageProblems, expectQuiet } from './support/console-guard';
import { documentTheme, fluentRootReady, resolvedPaletteColor } from './support/theme';

/**
 * U15 slice 2 (#1094) — `#/settings`.
 *
 * The page exists for one sentence. `resolveMasterKey` mints a master key on
 * first run when it finds neither `AUTONOMY_MASTER_KEY` nor a key file, and
 * warns that the file it just wrote now encrypts every secret at rest and must
 * be backed up — to `console.warn` and `fastify.log.warn`, and nowhere else. An
 * operator running this as a launchd service or a container never reads that.
 * Losing the file makes every stored secret permanently undecryptable, so these
 * specs are about whether the warning REACHES someone, which is a claim about
 * the rendered app and therefore only observable here.
 *
 * THIS HARNESS IS ALWAYS IN THE GENERATED STATE, by construction rather than by
 * luck: `playwright.config.ts` clears both `AUTONOMY_MASTER_KEY` and
 * `AUTONOMY_MASTER_KEY_FILE` (so an ambient credential cannot leak in) and
 * points `AUTONOMY_DATA_DIR` at a directory `reset-state.mjs` wipes as the
 * server's first act. So there is never a key file to find. The first spec
 * ASSERTS that rather than assuming it — if the harness ever stops guaranteeing
 * it, the advisory assertions below would silently stop testing anything, and a
 * loud failure is the only honest outcome.
 *
 * The `file` and `env` sources are NOT covered here: they need a differently
 * configured server process, which this single-server harness cannot offer.
 * `SettingsPage.test.tsx` owns all three sources, and `settings.test.ts` owns
 * the route's payload for each.
 */

/** The rail's toggle — the one that is on every route. */
function railToggle(page: import('@playwright/test').Page) {
  return page.getByRole('navigation', { name: 'Primary' }).getByRole('switch', { name: 'Dark mode' });
}

test('U15 — Settings names the auto-generated key file and says to back it up', async ({ page }) => {
  const problems = collectPageProblems(page);

  /* The SHIPPED wire, not `fastify.inject`. Two separate claims ride on it:
     the payload carries the key's provenance and NOTHING else (the route's
     whole security posture — a field that picked up key material would show
     up here), and the path the page renders is the one the server actually
     reported rather than anything the page invented. */
  const response = await page.request.get('/api/settings');
  expect(response.status()).toBe(200);
  const body = (await response.json()) as {
    masterKey: { source: string; keyFilePath: string | null };
  };
  expect(Object.keys(body)).toEqual(['masterKey']);
  expect(Object.keys(body.masterKey).sort()).toEqual(['keyFilePath', 'source']);
  expect(
    body.masterKey.source,
    'the e2e server starts against a wiped data dir with both master-key env vars cleared, so it must have generated its own key — see this file’s docblock',
  ).toBe('generated');
  const keyFilePath = body.masterKey.keyFilePath;
  expect(keyFilePath).not.toBeNull();

  /* Reached the way an operator reaches it: the rail's gear. The route is a
     sibling of the hubs, so no hub may light up on arrival. */
  await page.goto('/#/');
  await fluentRootReady(page);
  await page.getByRole('navigation', { name: 'Primary' }).getByRole('link', { name: 'Settings' }).click();

  await expect(page.getByRole('heading', { name: 'Settings', level: 2 })).toBeVisible();
  await expect(page).toHaveURL(/#\/settings$/);

  const secrets = page.getByRole('region', { name: 'Secret encryption' });
  await expect(secrets).toBeVisible();
  await expect(secrets).toContainText('Auto-generated by this server on first run');

  // The path is asserted against the SERVER's answer, so a hardcoded or
  // truncated render fails. `keyFilePath` is non-null per the assertion above.
  await expect(secrets.getByText(keyFilePath as string, { exact: true })).toBeVisible();

  /* The advisory itself. Matched on the CONSEQUENCE — the clause that makes an
     operator act — rather than on the whole paragraph, which would make this a
     copy of the wording instead of a test of it. */
  const advisory = secrets.getByText(/permanently undecryptable/i);
  await expect(advisory).toBeVisible();
  await expect(advisory).toContainText('back it up');

  /* COMPUTED, not eyeballed: `.status-advisory` must actually paint in the
     palette's warning colour. A mistyped or theme-scoped-wrong token leaves
     `color: var(--nope)` resolving to the inherited body text, which looks
     entirely plausible in a screenshot and strips the one visual cue that this
     paragraph is different from the prose around it. `resolvedPaletteColor`
     makes the browser resolve the token the only way it can — by painting
     with it — so the two sides are comparable `rgb(...)` strings. */
  const advisoryColor = await advisory.evaluate((el) => getComputedStyle(el).color);
  expect(advisoryColor).toBe(await resolvedPaletteColor(page, '--warning'));

  await expectQuiet(page, problems);
});

/**
 * The page's Appearance switch and the rail's are TWO components over ONE
 * store, which is exactly the arrangement that can go wrong invisibly: a second
 * copy of the state would leave both switches operable and disagreeing, and
 * would drive only half the app (the palette's `<html data-theme>` writes, but
 * not the `FluentProvider`'s theme PROP, which no DOM write can move).
 *
 * jsdom cannot see this — `SettingsPage.test.tsx` renders the page alone, so
 * there is no rail to disagree with it. Both switches on screen at once, and a
 * document that follows, is a claim only the real app can answer.
 */
test('U15 — the Settings theme switch and the rail’s are one control', async ({ page }) => {
  const problems = collectPageProblems(page);

  await page.goto('/#/settings');
  await fluentRootReady(page);

  const rail = railToggle(page);
  const onPage = page
    .getByRole('region', { name: 'Appearance' })
    .getByRole('switch', { name: 'Dark mode' });

  // Read the starting state rather than assuming it: the theme persists, and a
  // spec that ran before this one may have left it either way.
  const startedDark = await rail.isChecked();
  await expect(onPage).toBeChecked({ checked: startedDark });

  await onPage.click();
  await expect(rail).toBeChecked({ checked: !startedDark });
  await expect.poll(() => documentTheme(page)).toBe(startedDark ? 'light' : 'dark');

  // And back, driven from the RAIL this time — the page's switch must follow
  // the store in both directions, not merely publish to it.
  await rail.click();
  await expect(onPage).toBeChecked({ checked: startedDark });
  await expect.poll(() => documentTheme(page)).toBe(startedDark ? 'dark' : 'light');

  await expectQuiet(page, problems);
});
